In [7]:
import torch
from torch import nn
import numpy as np
import rasterio


In [25]:
def load_data(data_path, usage, is_label=False, apply_normalization=False, 
              normal_strategy="z_value", stat_procedure="gpb", global_stats=None, 
              dtype=np.float32, verbose=False):
    r"""
    Open data using gdal, read it as an array and normalize it.

    Arguments:
            data_path (string): Full path including filename of the data source we wish to load.
            usage (string): Either "train", "validation", "inference".
            is_label (binary): If True then the layer is a ground truth (category index) and if
                                set to False the layer is a reflectance band.
            apply_normalization (binary): If true min/max normalization will be applied on each band.
            normal_strategy (str): Strategy for normalization. Either 'min_max'
                               or 'z_value'.
            stat_procedure (str): Procedure to calculate the statistics used in normalization.
                              Options:
                                    - 'lab': local tile over all bands.
                                    - 'gab': global over all bands.
                                    - 'lpb': local tile per band.
                                    - 'gpb': global per band.
            global_stats (dict): Optional dictionary containing the 'min', 'max', 'mean', and 'std' arrays 
                                 for each band. If not provided, these values will be calculated from the data.
            dtype (np.dtype): Data type of the output image chips.
            verbose (binary): if set to true, print a screen statement on the loaded band.

    Returns:
            image: Returns the loaded image as a 32-bit float numpy ndarray.
    """

    # Inform user of the file names being loaded from the Dataset.
    if verbose:
        print('loading file:{}'.format(data_path))

    # open dataset using rasterio library.
    with rasterio.open(data_path, "r") as src:
        

        if is_label:
            if src.count != 1:
                raise ValueError("Expected Label to have exactly one channel.")
            img = src.read(1)
            return img

        else:
            print("Inside $$$$")
            meta = src.meta
            if apply_normalization:
                img = do_normalization(src.read(), normal_strategy, stat_procedure,
                                        bounds=(0, 1), clip_val=1, global_stats=global_stats)
                img = img.astype(dtype)
            else:
                img = src.read()
                img = img.astype(dtype)

    if usage in ["train", "validation"]:
        return img
    else:
        return img, meta

In [28]:
path="/shishir/All_Datasets/NASA-Crop-Classification/training_chips/chip_421_329_merged.tif"
k=load_data(path,usage="train")

Inside $$$$


In [29]:
k.shape

(18, 224, 224)

In [30]:
# !pip install tifffile


In [19]:
import tifffile

In [20]:
data = tifffile.imread(path)

In [22]:
data.shape

(224, 224, 18)

In [48]:
a=[[1,2,3],[4,-3,6]]

In [49]:
import numpy as np

In [50]:
a1=np.array(a)

In [46]:
l=a1.max()

In [47]:
l

6

In [51]:
a1[0]

array([1, 2, 3])

In [54]:
for r in range(len(a1)):
    for c in range(len(a1[0])):
        print(a1[r][c])

1
2
3
4
-3
6


In [55]:
mat=[["1","1","1","1","0"],["1","1","1","1","0"],["1","1","1","1","1"],["1","1","1","1","1"],["0","0","1","1","1"]]

In [56]:
mat

[['1', '1', '1', '1', '0'],
 ['1', '1', '1', '1', '0'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['0', '0', '1', '1', '1']]

In [57]:
m1=[["0","0","0","1"],["1","1","0","1"],["1","1","1","1"],["0","1","1","1"],["0","1","1","1"]]

In [58]:
m1

[['0', '0', '0', '1'],
 ['1', '1', '0', '1'],
 ['1', '1', '1', '1'],
 ['0', '1', '1', '1'],
 ['0', '1', '1', '1']]

In [59]:
m1=[["1","0","1","1","1"],["0","1","0","1","0"],["1","1","0","1","1"],["1","1","0","1","1"],["0","1","1","1","1"]]

In [60]:
m1

[['1', '0', '1', '1', '1'],
 ['0', '1', '0', '1', '0'],
 ['1', '1', '0', '1', '1'],
 ['1', '1', '0', '1', '1'],
 ['0', '1', '1', '1', '1']]

In [ ]:
[[1 0 1 1 1]
 [0 1 0 1 0]
 [1 1 0 1 1]
 [1 2 0 2 2]
 [0 2 2 2 3]]